#include "ARM7TDMI.h"

ARM7TDMI::ARM7TDMI() {
	using a = ARM7TDMI;
	cond_lookup = {
		{"EQ", &a::EQ}, {"NE", &a::NE}, {"CS", &a::CS}, {"CC", &a::CC}, {"MI", &a::MI},
		{"PL", &a::PL}, {"VS", &a::VS}, {"VC", &a::VC}, {"HI", &a::HI}, {"LS", &a::LS}, 
		{"GE", &a::GE}, {"LT", &a::LT}, {"GT", &a::GT}, {"LE", &a::LE}, {"AL", &a::AL},
		{"NV", &a::NV},
	};

	lookup = {
		{{"AND", &a::AND, &a::m1_LLI},  {"AND", &a::AND, &a::m1_LLR},  {"AND", &a::AND, &a::m1_LRI},  {"AND", &a::AND, &a::m1_LRR},  {"AND", &a::AND, &a::m1_ARI},  {"AND", &a::AND, &a::m1_ARR},  {"AND", &a::AND, &a::m1_RRI},  {"AND", &a::AND, &a::m1_RRR},  {"AND", &a::AND, &a::m1_LLI},  {"MUL", &a::MUL, &a::XXX},      {"AND", &a::AND, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_RGP}, {"AND", &a::AND, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"AND", &a::AND, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"ANDS", &a::AND, &a::m1_LLI}, {"ANDS", &a::AND, &a::m1_LLR}, {"ANDS", &a::AND, &a::m1_LRI}, {"ANDS", &a::AND, &a::m1_LRR}, {"ANDS", &a::AND, &a::m1_ARI}, {"ANDS", &a::AND, &a::m1_ARR}, {"ANDS", &a::AND, &a::m1_RRI}, {"ANDS", &a::AND, &a::m1_RRR}, {"ANDS", &a::AND, &a::m1_LLI}, {"MULS", &a::MUL, &a::XXX},     {"ANDS", &a::AND, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_RGP}, {"ANDS", &a::AND, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_RGP}, {"ANDS", &a::AND, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_RGP}},
		{{"EOR", &a::EOR, &a::m1_LLI},  {"EOR", &a::EOR, &a::m1_LLR},  {"EOR", &a::EOR, &a::m1_LRI},  {"EOR", &a::EOR, &a::m1_LRR},  {"EOR", &a::EOR, &a::m1_ARI},  {"EOR", &a::EOR, &a::m1_ARR},  {"EOR", &a::EOR, &a::m1_RRI},  {"EOR", &a::EOR, &a::m1_RRR},  {"EOR", &a::EOR, &a::m1_LLI},  {"MLA", &a::MLA, &a::XXX},      {"EOR", &a::EOR, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_RGP}, {"EOR", &a::EOR, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"EOR", &a::EOR, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"EORS", &a::EOR, &a::m1_LLI}, {"EORS", &a::EOR, &a::m1_LLR}, {"EORS", &a::EOR, &a::m1_LRI}, {"EORS", &a::EOR, &a::m1_LRR}, {"EORS", &a::EOR, &a::m1_ARI}, {"EORS", &a::EOR, &a::m1_ARR}, {"EORS", &a::EOR, &a::m1_RRI}, {"EORS", &a::EOR, &a::m1_RRR}, {"EORS", &a::EOR, &a::m1_LLI}, {"MLAS", &a::MUL, &a::XXX},     {"EORS", &a::EOR, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_RGP}, {"EORS", &a::EOR, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_RGP}, {"EORS", &a::EOR, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_RGP}},
		{{"SUB", &a::SUB, &a::m1_LLI},  {"SUB", &a::SUB, &a::m1_LLR},  {"SUB", &a::SUB, &a::m1_LRI},  {"SUB", &a::SUB, &a::m1_LRR},  {"SUB", &a::SUB, &a::m1_ARI},  {"SUB", &a::SUB, &a::m1_ARR},  {"SUB", &a::SUB, &a::m1_RRI},  {"SUB", &a::SUB, &a::m1_RRR},  {"SUB", &a::SUB, &a::m1_LLI},  {"???", &a::NOP, &a::XXX},      {"SUB", &a::SUB, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_IMP}, {"SUB", &a::SUB, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"SUB", &a::SUB, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"SUBS", &a::SUB, &a::m1_LLI}, {"SUBS", &a::SUB, &a::m1_LLR}, {"SUBS", &a::SUB, &a::m1_LRI}, {"SUBS", &a::SUB, &a::m1_LRR}, {"SUBS", &a::SUB, &a::m1_ARI}, {"SUBS", &a::SUB, &a::m1_ARR}, {"SUBS", &a::SUB, &a::m1_RRI}, {"SUBS", &a::SUB, &a::m1_RRR}, {"SUBS", &a::SUB, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"SUBS", &a::SUB, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_IMP}, {"SUBS", &a::SUB, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_IMP}, {"SUBS", &a::SUB, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_IMP}},
		{{"RSB", &a::RSB, &a::m1_LLI},  {"RSB", &a::RSB, &a::m1_LLR},  {"RSB", &a::RSB, &a::m1_LRI},  {"RSB", &a::RSB, &a::m1_LRR},  {"RSB", &a::RSB, &a::m1_ARI},  {"RSB", &a::RSB, &a::m1_ARR},  {"RSB", &a::RSB, &a::m1_RRI},  {"RSB", &a::RSB, &a::m1_RRR},  {"RSB", &a::RSB, &a::m1_LLI},  {"???", &a::NOP, &a::XXX},	    {"RSB", &a::RSB, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_IMP}, {"RSB", &a::RSB, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"RSB", &a::RSB, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"RSBS", &a::RSB, &a::m1_LLI}, {"RSBS", &a::RSB, &a::m1_LLR}, {"RSBS", &a::RSB, &a::m1_LRI}, {"RSBS", &a::RSB, &a::m1_LRR}, {"RSBS", &a::RSB, &a::m1_ARI}, {"RSBS", &a::RSB, &a::m1_ARR}, {"RSBS", &a::RSB, &a::m1_RRI}, {"RSBS", &a::RSB, &a::m1_RRR}, {"RSBS", &a::RSB, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"RSBS", &a::RSB, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_IMP}, {"RSBS", &a::RSB, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_IMP}, {"RSBS", &a::RSB, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_IMP}},
		{{"ADD", &a::ADD, &a::m1_LLI},  {"ADD", &a::ADD, &a::m1_LLR},  {"ADD", &a::ADD, &a::m1_LRI},  {"ADD", &a::ADD, &a::m1_LRR},  {"ADD", &a::ADD, &a::m1_ARI},  {"ADD", &a::ADD, &a::m1_ARR},  {"ADD", &a::ADD, &a::m1_RRI},  {"ADD", &a::ADD, &a::m1_RRR},  {"ADD", &a::ADD, &a::m1_LLI},  {"UMULL", &a::UMULL, &a::XXX},  {"ADD", &a::ADD, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_RGP}, {"ADD", &a::ADD, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"ADD", &a::ADD, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"ADDS", &a::ADD, &a::m1_LLI}, {"ADDS", &a::ADD, &a::m1_LLR}, {"ADDS", &a::ADD, &a::m1_LRI}, {"ADDS", &a::ADD, &a::m1_LRR}, {"ADDS", &a::ADD, &a::m1_ARI}, {"ADDS", &a::ADD, &a::m1_ARR}, {"ADDS", &a::ADD, &a::m1_RRI}, {"ADDS", &a::ADD, &a::m1_RRR}, {"ADDS", &a::ADD, &a::m1_LLI}, {"UMULLS", &a::UMULL, &a::XXX}, {"ADDS", &a::ADD, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_RGP}, {"ADDS", &a::ADD, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_RGP}, {"ADDS", &a::ADD, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_RGP}},
		{{"ADC", &a::ADC, &a::m1_LLI},  {"ADC", &a::ADC, &a::m1_LLR},  {"ADC", &a::ADC, &a::m1_LRI},  {"ADC", &a::ADC, &a::m1_LRR},  {"ADC", &a::ADC, &a::m1_ARI},  {"ADC", &a::ADC, &a::m1_ARR},  {"ADC", &a::ADC, &a::m1_RRI},  {"ADC", &a::ADC, &a::m1_RRR},  {"ADC", &a::ADC, &a::m1_LLI},  {"UMLAL", &a::UMLAL, &a::XXX},  {"ADC", &a::ADC, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_RGP}, {"ADC", &a::ADC, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"ADC", &a::ADC, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"ADCS", &a::ADC, &a::m1_LLI}, {"ADCS", &a::ADC, &a::m1_LLR}, {"ADCS", &a::ADC, &a::m1_LRI}, {"ADCS", &a::ADC, &a::m1_LRR}, {"ADCS", &a::ADC, &a::m1_ARI}, {"ADCS", &a::ADC, &a::m1_ARR}, {"ADCS", &a::ADC, &a::m1_RRI}, {"ADCS", &a::ADC, &a::m1_RRR}, {"ADCS", &a::ADC, &a::m1_LLI}, {"UMLALS", &a::UMLAL, &a::XXX}, {"ADCS", &a::ADC, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_RGP}, {"ADCS", &a::ADC, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_RGP}, {"ADCS", &a::ADC, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_RGP}},
		{{"SBC", &a::SBC, &a::m1_LLI},  {"SBC", &a::SBC, &a::m1_LLR},  {"SBC", &a::SBC, &a::m1_LRI},  {"SBC", &a::SBC, &a::m1_LRR},  {"SBC", &a::SBC, &a::m1_ARI},  {"SBC", &a::SBC, &a::m1_ARR},  {"SBC", &a::SBC, &a::m1_RRI},  {"SBC", &a::SBC, &a::m1_RRR},  {"SBC", &a::SBC, &a::m1_LLI},  {"SMULL", &a::SMULL, &a::XXX},  {"SBC", &a::SBC, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_IMP}, {"SBC", &a::SBC, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"SBC", &a::SBC, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"SBCS", &a::SBC, &a::m1_LLI}, {"SBCS", &a::SBC, &a::m1_LLR}, {"SBCS", &a::SBC, &a::m1_LRI}, {"SBCS", &a::SBC, &a::m1_LRR}, {"SBCS", &a::SBC, &a::m1_ARI}, {"SBCS", &a::SBC, &a::m1_ARR}, {"SBCS", &a::SBC, &a::m1_RRI}, {"SBCS", &a::SBC, &a::m1_RRR}, {"SBCS", &a::SBC, &a::m1_LLI}, {"SMULLS", &a::SMULL, &a::XXX}, {"SBCS", &a::SBC, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_IMP}, {"SBCS", &a::SBC, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_IMP}, {"SBCS", &a::SBC, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_IMP}},
		{{"RSC", &a::RSC, &a::m1_LLI},  {"RSC", &a::RSC, &a::m1_LLR},  {"RSC", &a::RSC, &a::m1_LRI},  {"RSC", &a::RSC, &a::m1_LRR},  {"RSC", &a::RSC, &a::m1_ARI},  {"RSC", &a::RSC, &a::m1_ARR},  {"RSC", &a::RSC, &a::m1_RRI},  {"RSC", &a::RSC, &a::m1_RRR},  {"RSC", &a::RSC, &a::m1_LLI},  {"SMLAL", &a::SMULL, &a::XXX},  {"RSC", &a::RSC, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_IMP}, {"RSC", &a::RSC, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"RSC", &a::RSC, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"RSCS", &a::RSC, &a::m1_LLI}, {"RSCS", &a::RSC, &a::m1_LLR}, {"RSCS", &a::RSC, &a::m1_LRI}, {"RSCS", &a::RSC, &a::m1_LRR}, {"RSCS", &a::RSC, &a::m1_ARI}, {"RSCS", &a::RSC, &a::m1_ARR}, {"RSCS", &a::RSC, &a::m1_RRI}, {"RSCS", &a::RSC, &a::m1_RRR}, {"RSCS", &a::RSC, &a::m1_LLI}, {"SMLALS", &a::SMULL, &a::XXX}, {"RSCS", &a::RSC, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_IMP}, {"RSCS", &a::RSC, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_IMP}, {"RSCS", &a::RSC, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_IMP}},
		{{"MRS", &a::MRS, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},	  {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"SWP", &a::SWP, &a::XXX},      {"???", &a::NOP, &a::XXX},     {"STRH", &a::STRH, &a::m3_RGO}, {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},        {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX}},
		{{"TSTS", &a::TST, &a::m1_LLI}, {"TSTS", &a::TST, &a::m1_LLR}, {"TSTS", &a::TST, &a::m1_LRI}, {"TSTS", &a::TST, &a::m1_LRR}, {"TSTS", &a::TST, &a::m1_ARI}, {"TSTS", &a::TST, &a::m1_ARR}, {"TSTS", &a::TST, &a::m1_RRI}, {"TSTS", &a::TST, &a::m1_RRR}, {"TSTS", &a::TST, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"TSTS", &a::TST, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_RGO}, {"TSTS", &a::TST, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_RGO}, {"TSTS", &a::TST, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_RGO}},
		{{"MSR", &a::MSR, &a::XXX},     {"BX", &a::BX, &a::XXX},       {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},      {"???", &a::NOP, &a::XXX},     {"STRH", &a::STRH, &a::m3_PRG}, {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},        {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX}},
		{{"TEQS", &a::TEQ, &a::m1_LLI}, {"TEQS", &a::TEQ, &a::m1_LLR}, {"TEQS", &a::TEQ, &a::m1_LRI}, {"TEQS", &a::TEQ, &a::m1_LRR}, {"TEQS", &a::TEQ, &a::m1_ARI}, {"TEQS", &a::TEQ, &a::m1_ARR}, {"TEQS", &a::TEQ, &a::m1_RRI}, {"TEQS", &a::TEQ, &a::m1_RRR}, {"TEQS", &a::TEQ, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"TEQS", &a::TEQ, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_PRG}, {"TEQS", &a::TEQ, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_PRG}, {"TEQS", &a::TEQ, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_PRG}},
		{{"MRS", &a::MRS, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},	  {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"SWPB", &a::SWPB, &a::XXX},    {"???", &a::NOP, &a::XXX},     {"STRH", &a::STRH, &a::m3_IMO}, {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},        {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX}},
		{{"CMPS", &a::CMP, &a::m1_LLI}, {"CMPS", &a::CMP, &a::m1_LLR}, {"CMPS", &a::CMP, &a::m1_LRI}, {"CMPS", &a::CMP, &a::m1_LRR}, {"CMPS", &a::CMP, &a::m1_ARI}, {"CMPS", &a::CMP, &a::m1_ARR}, {"CMPS", &a::CMP, &a::m1_RRI}, {"CMPS", &a::CMP, &a::m1_RRR}, {"CMPS", &a::CMP, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"CMPS", &a::CMP, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_IMO}, {"CMPS", &a::CMP, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_IMO}, {"CMPS", &a::CMP, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_IMO}},
		{{"MSR", &a::MSR, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},      {"???", &a::NOP, &a::XXX},     {"STRH", &a::STRH, &a::m3_PIM}, {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX},        {"???", &a::NOP, &a::XXX},     {"???", &a::NOP, &a::XXX}},
		{{"CMNS", &a::CMN, &a::m1_LLI}, {"CMNS", &a::CMN, &a::m1_LLR}, {"CMNS", &a::CMN, &a::m1_LRI}, {"CMNS", &a::CMN, &a::m1_LRR}, {"CMNS", &a::CMN, &a::m1_ARI}, {"CMNS", &a::CMN, &a::m1_ARR}, {"CMNS", &a::CMN, &a::m1_RRI}, {"CMNS", &a::CMN, &a::m1_RRR}, {"CMNS", &a::CMN, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"CMNS", &a::CMN, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_PIM}, {"CMNS", &a::CMN, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_PIM}, {"CMNS", &a::CMN, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_PIM}},
		{{"ORR", &a::ORR, &a::m1_LLI},  {"ORR", &a::ORR, &a::m1_LLR},  {"ORR", &a::ORR, &a::m1_LRI},  {"ORR", &a::ORR, &a::m1_LRR},  {"ORR", &a::ORR, &a::m1_ARI},  {"ORR", &a::ORR, &a::m1_ARR},  {"ORR", &a::ORR, &a::m1_RRI},  {"ORR", &a::ORR, &a::m1_RRR},  {"ORR", &a::ORR, &a::m1_LLI},  {"???", &a::NOP, &a::XXX},      {"ORR", &a::ORR, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_RGO}, {"ORR", &a::ORR, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"ORR", &a::ORR, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"ORRS", &a::ORR, &a::m1_LLI}, {"ORRS", &a::ORR, &a::m1_LLR}, {"ORRS", &a::ORR, &a::m1_LRI}, {"ORRS", &a::ORR, &a::m1_LRR}, {"ORRS", &a::ORR, &a::m1_ARI}, {"ORRS", &a::ORR, &a::m1_ARR}, {"ORRS", &a::ORR, &a::m1_RRI}, {"ORRS", &a::ORR, &a::m1_RRR}, {"ORRS", &a::ORR, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"ORRS", &a::ORR, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_RGO}, {"ORRS", &a::ORR, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_RGO}, {"ORRS", &a::ORR, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_RGO}},
		{{"MOV", &a::MOV, &a::m1_LLI},  {"MOV", &a::MOV, &a::m1_LLR},  {"MOV", &a::MOV, &a::m1_LRI},  {"MOV", &a::MOV, &a::m1_LRR},  {"MOV", &a::MOV, &a::m1_ARI},  {"MOV", &a::MOV, &a::m1_ARR},  {"MOV", &a::MOV, &a::m1_RRI},  {"MOV", &a::MOV, &a::m1_RRR},  {"MOV", &a::MOV, &a::m1_LLI},  {"???", &a::NOP, &a::XXX},      {"MOV", &a::MOV, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_PRG}, {"MOV", &a::MOV, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"MOV", &a::MOV, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"MOVS", &a::MOV, &a::m1_LLI}, {"MOVS", &a::MOV, &a::m1_LLR}, {"MOVS", &a::MOV, &a::m1_LRI}, {"MOVS", &a::MOV, &a::m1_LRR}, {"MOVS", &a::MOV, &a::m1_ARI}, {"MOVS", &a::MOV, &a::m1_ARR}, {"MOVS", &a::MOV, &a::m1_RRI}, {"MOVS", &a::MOV, &a::m1_RRR}, {"MOVS", &a::MOV, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"MOVS", &a::MOV, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_PRG}, {"MOVS", &a::MOV, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_PRG}, {"MOVS", &a::MOV, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_PRG}},
		{{"BIC", &a::BIC, &a::m1_LLI},  {"BIC", &a::BIC, &a::m1_LLR},  {"BIC", &a::BIC, &a::m1_LRI},  {"BIC", &a::BIC, &a::m1_LRR},  {"BIC", &a::BIC, &a::m1_ARI},  {"BIC", &a::BIC, &a::m1_ARR},  {"BIC", &a::BIC, &a::m1_RRI},  {"BIC", &a::BIC, &a::m1_RRR},  {"BIC", &a::BIC, &a::m1_LLI},  {"???", &a::NOP, &a::XXX},      {"BIC", &a::BIC, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_IMO}, {"BIC", &a::BIC, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"BIC", &a::BIC, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"BICS", &a::BIC, &a::m1_LLI}, {"BICS", &a::BIC, &a::m1_LLR}, {"BICS", &a::BIC, &a::m1_LRI}, {"BICS", &a::BIC, &a::m1_LRR}, {"BICS", &a::BIC, &a::m1_ARI}, {"BICS", &a::BIC, &a::m1_ARR}, {"BICS", &a::BIC, &a::m1_RRI}, {"BICS", &a::BIC, &a::m1_RRR}, {"BICS", &a::BIC, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"BICS", &a::BIC, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_IMO}, {"BICS", &a::BIC, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_IMO}, {"BICS", &a::BIC, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_IMO}},
		{{"MVN", &a::MVN, &a::m1_LLI},  {"MVN", &a::MVN, &a::m1_LLR},  {"MVN", &a::MVN, &a::m1_LRI},  {"MVN", &a::MVN, &a::m1_LRR},  {"MVN", &a::MVN, &a::m1_ARI},  {"MVN", &a::MVN, &a::m1_ARR},  {"MVN", &a::MVN, &a::m1_RRI},  {"MVN", &a::MVN, &a::m1_RRR},  {"MVN", &a::MVN, &a::m1_LLI},  {"???", &a::NOP, &a::XXX},      {"MVN", &a::MVN, &a::m1_LRI},  {"STRH", &a::STRH, &a::m3_PIM}, {"MVN", &a::MVN, &a::m1_ARI},  {"???", &a::NOP, &a::XXX},        {"MVN", &a::MVN, &a::m1_RRI},  {"???", &a::NOP, &a::XXX}},
		{{"MVNS", &a::MVN, &a::m1_LLI}, {"MVNS", &a::MVN, &a::m1_LLR}, {"MVNS", &a::MVN, &a::m1_LRI}, {"MVNS", &a::MVN, &a::m1_LRR}, {"MVNS", &a::MVN, &a::m1_ARI}, {"MVNS", &a::MVN, &a::m1_ARR}, {"MVNS", &a::MVN, &a::m1_RRI}, {"MVNS", &a::MVN, &a::m1_RRR}, {"MVNS", &a::MVN, &a::m1_LLI}, {"???", &a::NOP, &a::XXX},      {"MVNS", &a::MVN, &a::m1_LRI}, {"LDRH", &a::LDRH, &a::m3_PIM}, {"MVNS", &a::MVN, &a::m1_ARI}, {"LDRSB", &a::LDRSB, &a::m3_PIM}, {"MVNS", &a::MVN, &a::m1_RRI}, {"LDRSH", &a::LDRSH, &a::m3_PIM}},
		{{"AND", &a::AND, &a::m1_IMM}},
		{{"ANDS", &a::AND, &a::m1_IMM}},
		{{"EOR", &a::EOR, &a::m1_IMM}},
		{{"EORS", &a::EOR, &a::m1_IMM}},
		{{"SUB", &a::SUB, &a::m1_IMM}},
		{{"SUBS", &a::SUB, &a::m1_IMM}},
	};
}

ARM7TDMI::~ARM7TDMI() {

}
